src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    post_list,
    post_delete,
    post_create,
    post_detail,
    post_update
)

urlpatterns = [
    url(r'^$', post_list, name='post_list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

src/trydjango19/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
# Create your models here.

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object,
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              height_field="height_field",
                              width_field="width_field")
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={"slug": self.slug})
        # return "/posts/%s/" % self.id
    class Meta:
        ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)

    if new_slug is not None:
        slug = new_slug
    query_set = Post.objects.filter(slug=slug).order_by("-id")
    exists = query_set.exists()
    if exists:
        new_slug = "%s-%s" % (slug, query_set.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(instance, sender, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
__author__ = 'amir'

from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'draft', 'publish']
        widgets = {
            'publish': forms.DateInput(attrs={'class': 'datetime-input'})
        }

src/posts/views.py
from urllib import quote_plus
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PostForm
from .models import Post


def post_list(request):
    today = timezone.now().date()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    else:
        queryset_list = Post.objects.active()
    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()

    paginator = Paginator(queryset_list, 2) # Show 10 posts per page

    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "object_list": queryset,
        "title": 'Blog Posts',
        'page_request_var': page_request_var,
        'today': today
    }

    return render(request, "post_list.html", context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    context = {"title": instance.title, "instance": instance, "share_string": share_string}
    return render(request, "post_detail.html", context)


def post_update(request, slug=None):
    # referer_url = request.META['HTTP_REFERER']
    current_url = request.path
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Post <a href='#'>updated</a> successfully", extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url())


    context = {"title": instance.title, "instance": instance, "form": form, "current_url": current_url}
    return render(request, "post_form.html", context)


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Post created successfully")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {'form': form}
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Post deleted successfully")
    return redirect("posts:post_list")

src/templates/base.html
{% load staticfiles %}
<!-- DOCTYPE html -->
<html>
    <head>
        <title>{% block head_title %}Try Django 1.9 {% endblock head_title %}</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
         <!-- Latest compiled and minified JavaScript -->
        <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
        <script
          src="https://code.jquery.com/jquery-3.2.1.min.js"
          integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
          crossorigin="anonymous"></script>
        <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
        <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
        <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
{#        <style> {% block style %}{% endblock style %}</style>#}

    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        {% include "messages_display.html" %}
        <div class="container">
            {% block content %}{% endblock content %}
        </div>


    </body>
</html>

src/templates/messages_display.html
{% if messages %}

    <div class="message">
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}> {% if 'html_safe' in message.tags %}{{ message|safe }} {% else %} {{ message }} {% endif %}</li>
        {% endfor %}
        </ul>
    </div>
{% endif %}

src/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        {% if instance.image %}
        <img src="{{ instance.image.url }}" alt="image"/>
        {% endif %}
        <hr/>
        <h1>{{ title }} <small>{% if instance.draft %} <span style="color: #e4080c">Draft</span> {% endif %}{{instance.publish }}</small></h1>
        {% if instance.user.get_full_name %}<p>Author: {{ instance.user.get_full_name }}</p> {% endif %}
        <p><div class="fb-like" data-href={{ request.build_absolute_uri }} data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
        <hr/>
{#        <p>#}
{#            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">#}
{#            Facebook#}
{#            </a>#}
{##}
{#            <a href="https://twitter.com/home?status={{ instance.content | urlify }}20{{ request.build_absolute_uri }}">#}
{#            Twitter#}
{#            </a>#}
{##}
{#            <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Google+</a>#}
{##}
{##}
{#            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">#}
{#            Linkedin#}
{#            </a>#}
{#        </p>#}

        <div class="row">
            <div class="col-sm-12">
                {{instance.content | linebreaks}}
                <p><a href="{% url 'posts:update' slug=instance.slug %}" class="btn btn-primary" role="button"> Edit Post </a> </p>

            </div>
        </div>
        <hr/>
        <br/>
        <div class="fb-comments" data-href={{ request.build_absolute_uri }} data-numposts="5"></div>

    </div>
{% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Form:</h1>
        {{current_url}}

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type='submit' class="btn btn-primary" value="Create Post"/>
        </form>
    </div>
     <script>
        $(function () {
            $('.datetime-input').datetimepicker({
                format:'YYYY-MM-DD'
            });
        });
    </script>

{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
    <h1>{{ title }}</h1>

    <form method="get" action="">
        <input type="text" placeholder="search here.." name="q" value="{{ request.GET.q }}"/>
        <input type="submit" value="Search"/>
    </form>
        {% for obj in object_list %}
            <div class="row">
              <div class="col-sm-12">
                <div class="thumbnail">
                    {% if obj.image %}
                    <img src="{{ obj.image.url }}" alt="image"/>
                    {% endif %}
                  <div class="caption">
                    {% if obj.draft %}<h3 style="color: #a41515"> Draft </h3>{% endif %} {% if obj.publish > today %} <h3> Future Post </h3> {% endif %}
                    <h3><a href="{{ obj.get_absolute_url }}"> {{obj.title}} </a> <smal>{{obj.publish}}</smal></h3>
                      {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p> {% endif %}
                    <p>{{obj.content | linebreaks | truncatechars:80}}</p>
                    <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View Details</a> </p>
                  </div>
                </div>
              </div>
            <hr/>
            </div>

        {%endfor%}
    <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
            {% endif %}
        </span>
    </div>
    </div>

{% endblock content %}